---
tap_install:
  values:
    profile: build
    shared:
      ingress_domain: "tap.gitbuild.mss.dapd.net"
      kubernetes_distribution: openshift
      kubernetes_version: 1.25.0
    ceip_policy_disclosed: true
    supply_chain: basic
    metadata_store:
      ns_for_export_app_cert: "my-apps"
      app_service_type: ClusterIP
    scanning:
      metadataStore:
        url: ""
    grype:
      namespace: default
